// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function text(value) {
  return {
    content: [
      { type: "text", text: typeof value === "string" ? value : JSON.stringify(value, null, 2) }
    ]
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-businesses.ts
var list_businesses_default = defineTool({
  name: "list_businesses",
  title: "List my businesses",
  description: "List the Qblink businesses owned by the signed-in user, with id, name, category and live-visibility settings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("businesses").select("id,name,category,address,discovery_enabled,remote_joining_enabled,show_live_queue_info,created_at").eq("owner_id", ctx.getUserId()).order("created_at", { ascending: true });
    if (error) return fail(error.message);
    return { ...text(data ?? []), structuredContent: { businesses: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-queues.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_queues_default = defineTool2({
  name: "list_queues",
  title: "List queues for a business",
  description: "List the queues (counters) of a business owned by the signed-in user, including type, status and seating configuration.",
  inputSchema: {
    business_id: z.string().uuid().describe("Business id from list_businesses."),
    include_internal: z.boolean().nullable().describe("Include internal table-size child queues. Defaults to false (counters only).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, include_internal }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    let query = supabaseForUser(ctx).from("queues").select("id,name,status,queue_type,seating_policy,current_token,next_token,estimated_service_time,parent_queue_id,table_size").eq("business_id", business_id).order("created_at", { ascending: true });
    if (!include_internal) query = query.is("parent_queue_id", null);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return { ...text(data ?? []), structuredContent: { queues: data ?? [] } };
  }
});

// src/lib/mcp/tools/queue-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var queue_status_default = defineTool3({
  name: "get_queue_status",
  title: "Get live queue status",
  description: "Live snapshot of one queue: now serving token, number waiting, average wait so far and estimated wait for a new joiner.",
  inputSchema: { queue_id: z2.string().uuid().describe("Queue id from list_queues.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ queue_id }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: queue, error: qErr } = await supabase.from("queues").select("id,name,status,current_token,next_token,estimated_service_time,queue_type").eq("id", queue_id).maybeSingle();
    if (qErr) return fail(qErr.message);
    if (!queue) return fail("Queue not found or not accessible to this user.");
    const { data: visitors, error: vErr } = await supabase.from("queue_visitors").select("status,joined_at,served_at").eq("queue_id", queue_id);
    if (vErr) return fail(vErr.message);
    const rows = visitors ?? [];
    const waiting = rows.filter((v) => v.status === "waiting" || v.status === "checked_in").length;
    const served = rows.filter((v) => v.status === "served" && v.served_at);
    const avgServiceMinutes = served.length ? Math.round(
      served.reduce(
        (sum, v) => sum + (new Date(v.served_at).getTime() - new Date(v.joined_at).getTime()) / 6e4,
        0
      ) / served.length
    ) : queue.estimated_service_time ?? 5;
    const snapshot = {
      queue_id: queue.id,
      queue_name: queue.name,
      queue_status: queue.status,
      now_serving: queue.current_token,
      people_waiting: waiting,
      served_today: served.length,
      average_wait_minutes: avgServiceMinutes,
      estimated_wait_for_new_joiner_minutes: waiting * (queue.estimated_service_time ?? 5)
    };
    return { ...text(snapshot), structuredContent: snapshot };
  }
});

// src/lib/mcp/tools/list-waiting-visitors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_waiting_visitors_default = defineTool4({
  name: "list_waiting_visitors",
  title: "List waiting visitors",
  description: "List the people currently in a queue, in join order, with token number, status, party size and how long they have waited.",
  inputSchema: {
    queue_id: z3.string().uuid().describe("Queue id from list_queues."),
    limit: z3.number().int().min(1).max(100).nullable().describe("Max rows to return. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ queue_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("queue_visitors").select("token_number,visitor_name,status,party_size,assigned_table_size,joined_at,called_at").eq("queue_id", queue_id).in("status", ["waiting", "checked_in", "called", "serving"]).order("token_number", { ascending: true }).limit(limit ?? 25);
    if (error) return fail(error.message);
    const now = Date.now();
    const rows = (data ?? []).map((v) => ({
      ...v,
      waiting_minutes: Math.round((now - new Date(v.joined_at).getTime()) / 6e4)
    }));
    return { ...text(rows), structuredContent: { visitors: rows } };
  }
});

// src/lib/mcp/tools/business-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var business_summary_default = defineTool5({
  name: "get_business_today_summary",
  title: "Today's flow summary",
  description: "Aggregate today's customer flow for a business: visitors joined, served, no-shows, cancelled, currently waiting and busiest hour.",
  inputSchema: { business_id: z4.string().uuid().describe("Business id from list_businesses.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: queues, error: qErr } = await supabase.from("queues").select("id,name").eq("business_id", business_id);
    if (qErr) return fail(qErr.message);
    const ids = (queues ?? []).map((q) => q.id);
    if (ids.length === 0) return fail("No queues found for this business, or it is not accessible to this user.");
    const since = /* @__PURE__ */ new Date();
    since.setHours(0, 0, 0, 0);
    const { data, error } = await supabase.from("queue_visitors").select("status,joined_at,served_at").in("queue_id", ids).gte("joined_at", since.toISOString());
    if (error) return fail(error.message);
    const rows = data ?? [];
    const byHour = /* @__PURE__ */ new Map();
    for (const r of rows) {
      const h = new Date(r.joined_at).getHours();
      byHour.set(h, (byHour.get(h) ?? 0) + 1);
    }
    const busiest = [...byHour.entries()].sort((a, b) => b[1] - a[1])[0];
    const count = (s) => rows.filter((r) => r.status === s).length;
    const summary = {
      business_id,
      queues: queues?.length ?? 0,
      joined_today: rows.length,
      currently_waiting: count("waiting") + count("checked_in"),
      served: count("served"),
      no_shows: count("no_show"),
      cancelled: count("cancelled"),
      busiest_hour: busiest ? `${String(busiest[0]).padStart(2, "0")}:00` : null,
      busiest_hour_joins: busiest ? busiest[1] : 0
    };
    return { ...text(summary), structuredContent: summary };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fvhkpxxahpcofhasfukc";
var mcp_default = defineMcp({
  name: "qblink-mcp",
  title: "Qblink",
  version: "0.1.0",
  instructions: "Tools for Qblink, a customer flow intelligence platform for walk-in businesses. Start with `list_businesses` to find the signed-in owner's businesses, then `list_queues` for their counters, `get_queue_status` for a live snapshot, `list_waiting_visitors` for who is in line, and `get_business_today_summary` for today's flow totals. All tools are read-only and scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_businesses_default, list_queues_default, queue_status_default, list_waiting_visitors_default, business_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
